# Generated by Django 5.1.3 on 2024-12-08 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subdomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subdomain name, e.g., 'blog'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        help_text="Describe the purpose of this subdomain."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                            ("pending", "Pending Approval"),
                        ],
                        default="pending",
                        help_text="Status of the subdomain.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the subdomain was requested."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the subdomain was last updated."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who requested this subdomain.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdomains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subdomain",
                "verbose_name_plural": "Subdomains",
                "ordering": ["-created_at"],
            },
        ),
    ]
